USE Berry_DB
GO

/*
CHOOSE() FUNCTION IN SQL SERVER 2012
--It return the item at specified index from the list of available values.
--the index position starts with 1 not zero
*/

SELECT *, CASE DATEPART(MM,DOB)  
WHEN 1 THEN'JAN'
WHEN 2 THEN 'FEB'
WHEN 3 THEN'MAR'
WHEN 4 THEN 'APR'
WHEN 5 THEN'MAY'
WHEN 6 THEN 'JUN'
WHEN 7 THEN'JUL'
WHEN 8 THEN'AUG'
WHEN 9 THEN'SEP'
WHEN 10 THEN 'OCT'
WHEN 11 THEN'NOV'
WHEN 12 THEN 'DEC' END AS MONTH_DOB
FROM EMPLOYEE

SELECT * ,CHOOSE(DATEPART(MM,DOB) ,'JAN', 'FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC') AS MONTH_DOB FROM EMPLOYEE

