	SELECT * FROM SALES

	SELECT Agent ,Country ,SUM(SALES) AS TotalAmount FROM  SALES
	GROUP BY dbo.SALES.AGENT,COUNTRY
	UNION
	SELECT Agent ,NULL ,SUM(SALES) AS TotalAmount FROM  SALES
	GROUP BY AGENT
	UNION
	SELECT NULL ,COUNTRY ,SUM(SALES) AS TotalAmount FROM  SALES
	GROUP BY COUNTRY
	UNION
	SELECT NULL ,NULL ,SUM(SALES) AS TotalAmount FROM  SALES 	ORDER BY AGENT ASC

	---Grouping sets introduced oin SQL server 2008

	SELECT Agent ,Country ,SUM(SALES) AS TotalAmount FROM  SALES
	GROUP BY
	GROUPING SETS	
	((AGENT,COUNTRY)
	,(AGENT)
	,(COUNTRY)
	,()
	)
	ORDER BY AGENT ASC
