SELECT * FROM ALL_TAB_COLUMNS
WHERE OWNER = 'MARY' 
AND TABLE_NAME LIKE 'M%'
--NOT LIKE 'BIN%'

--SELECT * FROM BIN$yv2h/T6IS5uVK5CMupyK7Q==$0

SELECT * FROM EMP_DET_TARGET

SELECT * FROM MAX_SAL_EMP;

SELECT * FROM V$VERSION