USE berry_DB

CREATE TABLE DEPARTMENT
(ID INT PRIMARY KEY IDENTITY(1,1)
,NAME nvarchar(10)
)

CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY IDENTITY,
NAME nvarchar(10),
GENDER NVARCHAR(10),
DEPTID INT FOREIGN KEY REFERENCES dbo.DEPARTMENT(ID)
)

CREATE PROC SP_GETEMPLOYEES
AS
BEGIN
		SELECT * FROM dbo.EMPLOYEE e
END


CREATE PROC SP_GETEMP_DEPT
AS
BEGIN
SELECT E.NAME AS EMPLOYEENAME ,D.NAME AS DEPARTMENT_NAME FROM EMPLOYEE E
INNER JOIN dbo.DEPARTMENT D ON E.ID = D.ID
END

CREATE VIEW Vw_Department
AS
	SELECT * FROM dbo.DEPARTMENT 
GO

	SELECT * FROM Vw_Department

CREATE FUNCTION fn_GETEMP_DEPT()
RETURNS TABLE
AS
RETURN
SELECT E.NAME AS EMPLOYEENAME ,D.NAME AS DEPARTMENT_NAME FROM EMPLOYEE E
INNER JOIN dbo.DEPARTMENT D ON E.ID = D.ID

 -------------------------------------------

	SELECT * FROM SYS.DM_SQL_REFERENCING_ENTITIES('[dbo].[DEPARTMENT]','OBJECT')
	SELECT * FROM SYS.DM_SQL_REFERENCED_ENTITIES('dbo.DEPARTMENT','OBJECT')
	SELECT * FROM SYS.DM_SQL_REFERENCING_ENTITIES('dbo.EMPLOYEE','OBJECT')
	SELECT * FROM SYS.DM_SQL_REFERENCED_ENTITIES('dbo.EMPLOYEE','OBJECT')

	SELECT * FROM SYS.DM_SQL_REFERENCED_ENTITIES('DBO.SP_GETEMP_DEPT','OBJECT')

	sp_depends 'SP_GETEMP_DEPT'

	sp_depends 'dbo.DEPARTMENT'
	 